name: app_group_directory
description: >-
  Retrieve App Group directory on iOS.
  Port of FileManager.containerURL to Flutter.
version: 2.0.0
homepage: https://github.com/Albert221/app_group_directory

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: me.wolszon.app_group_directory
        pluginClass: AppGroupDirectoryPlugin
      ios:
        pluginClass: AppGroupDirectoryPlugin

